### ISSUE TITLE
Compare view renders no change for record with path change

### ISSUE THREAD

**Issue by themightychris** [JarvusInnovations/gitsheets#13]
With a path template of `{{Grade}}/{{StudentNumber}}` I changed a first name in two rows and that shows in a diff, but for a 3rd record I just changed the grade and no diff shows. I found the row with its original value for Grade in the table with no highlight

**Comment by timwis** [comment]
Ah, git treats this as a rename rather than a modification, so we were ignoring it. I've got it treating renames basically the same as modifications now, though I'm running into issues with what gets rendered because the primary key has changed, so it doesn't know how to associate the diff with the original record being displayed in the table. Gotta rethink and refactor a bit 🤔

**Comment by timwis** [comment]
Wasn't as complex as I thought; we're always presenting the diffs on top of `srcRef`/state_a, so the diffs just need to use the `srcRef` key.

I've got this fixed in the `hotfix/renames` branch, but I'd like to clean it up before merging.
